name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get the version
        id: vars
        run: "echo ::set-output name=tag::$(git rev-parse --short HEAD)"

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{secrets.REGISTRY_USERNAME }}
          password: ${{secrets.REGISTRY_PASSWORD }}

      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/jhu-library-operations/mysql:latest
            ghcr.io/jhu-library-operations/mysql:${{steps.vars.outputs.tag}}
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
